### ISSUE TITLE
parse setting.json with comment

### ISSUE THREAD

**Issue by MarekLew** [Devine-Davies/vs-make-hidden#2]
Where comment is in `setting.json` then extension don't work:

```
[devine-davies.make-hidden] Unexpected token / in JSON at position 829: SyntaxError: Unexpected token / in JSON at position 829
	at JSON.parse (<anonymous>)
	at fs.readFile (C:\Users\MyUser\.vscode\extensions\devine-davies.make-hidden-0.32.0\out\src\make-hidden\make-hidden.provider.js:69:47)
	at tryToString (fs.js:449:3)
	at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

Problem is parse comment.

**Comment by MarekLew** [comment]
Please copy the file or alert you to change but do not delete the contents.

**Comment by alexkuc** [comment]
I am not sure if this issue is related to this extension as [json does not support comments in general](https://stackoverflow.com/questions/244777/can-comments-be-used-in-json)

**Comment by MarekLew** [comment]
No. VSC support setting.json with comment, but this extension use another
parser and wrong use it. As far as I remember.

pt., 5 mar 2021, 02:05 użytkownik Alexander Kucheryuk <
notifications@github.com> napisał:
